---
version: '2'
services:
  server:
    build: .
    working_dir: /src
    command: "/usr/bin/mvn compile exec:java"
    ports:
      - "57001:57001"
    volumes:
      - ".:/src"
      - "~/.m2:/root/.m2"

  local:
    build: .
    working_dir: /src
    command: "/usr/bin/mvn -Dsimulation=LookupLocal test"
    env_file: .env
    volumes:
      - ".:/src"
      - "~/.m2:/root/.m2"

  blocking:
    build: .
    working_dir: /src
    command: "/usr/bin/mvn -Dsimulation=LookupBlocking test"
    env_file: .env
    volumes:
      - ".:/src"
      - "~/.m2:/root/.m2"

  async:
    build: .
    working_dir: /src
    command: "/usr/bin/mvn -Dsimulation=LookupAsync test"
    env_file: .env
    volumes:
      - ".:/src"
      - "~/.m2:/root/.m2"
